CREATE TABLE IF NOT EXISTS ks_tsc.tb_anagrafica(
	ab_codi varchar,
	matricola varchar,
	nominativo varchar,
	indirizzo varchar,
	comune varchar,
	provincia varchar,
	cap varchar,
	telefono varchar,
	cellulare varchar,
	sesso varchar,
	data_nascita time,
	luogo_nascita varchar,
	altezza int,
	peso int,
	patologia varchar,
	terapia varchar,
	evidenzia varchar,
	note varchar,
	altro text,
	dati_abita text,
	sopravvivenza text,
	dati_tecnici text,
	data_inserimento timestamp,
	data_installazione timestamp,
	data_modifica timestamp,
	data_aggiornamento timestamp,
	data_disinstallazione timestamp,
	motivo_disinstallazione text,
	centrale varchar,
	ente varchar,
  	PRIMARY KEY (ab_codi)
);

--DROP TABLE IF EXISTS ks_tsc.tb_anagrafica;