SELECT
`AB_CODI`,
`MATRICOLA`,
`NOMINATIVO`,
`INDIRIZZO`,
`COMUNE`,
`PROVINCIA`,
`CAP`,
`TELEFONO`,
`CELLULARE`,
`SESSO`,
`DATA_NASCITA`,
`LUOGO_NASCITA`,
`ALTEZZA`,
`PESO`,
`PATOLOGIA`,
`TERAPIA`,
`EVIDENZIA`,
`NOTE`,
`ALTRO`
,`DATI_ABITA`,
`SOPRAVVIVENZA`,
`DATI_TECNICI`,
`DATA_INSERIMENTO`,
`DATA_INSTALLAZIONE`,
`DATA_MODIFICA`,
`DATA_AGGIORNAMENTO`,
`DATA_DISINSTALLAZIONE`,
`MOTIVO_DISINSTALLAZIONE`,
`CENTRALE`,
`ENTE`
INTO OUTFILE '/home/astraservice/Documents/tsc/export/anagrafica.csv'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
FROM anagrafica;